Algoritmo "Exibir Mensagem"
// Disciplina   :[Lógica de Programação e Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exibir uma Mensagem
// Autor(a)    : Sergio
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Sergio - São Paulo")
Escreval ("Equipe 04")
Escreva ("Sergio")


Fimalgoritmo